package View;

import Controller.StudentMarkController;
import Entity.StudentMark;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MarkManagerStudentFrame extends javax.swing.JFrame {

    private DefaultTableModel defaultTableModel;
    private StudentMarkController studentMarkController;
    private StudentMark studentMark;

    /**
     * Creates new form MarkManagerStudentFrame
     */
    public MarkManagerStudentFrame() {

        initComponents();
        studentMarkController = new StudentMarkController();
        studentMark = new StudentMark();

        defaultTableModel = new DefaultTableModel() {
            @Override
            //Khong cho nguoi dung sua truc tiep tren table
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }

        };
        //sua cho nay lai
        studenttablemark.setModel(defaultTableModel);
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Name");
        defaultTableModel.addColumn("TenMon");
        defaultTableModel.addColumn("DiemThanhPhan");
        defaultTableModel.addColumn("DiemGiuaKy");
        defaultTableModel.addColumn("DiemThi");
        defaultTableModel.addColumn("DiemTongKet");
        defaultTableModel.addColumn("XepLoai");
        defaultTableModel.addColumn("MaMonHoc");
        setdata(studentMarkController.getAllMark());

    }

    private void setdata(List<StudentMark> studentMark) {
        for (StudentMark studentmark : studentMark) {
            defaultTableModel.addRow(new Object[]{
                studentmark.getId(),
                studentmark.getName(),
                studentmark.getTenMonHoc(),
                studentmark.getDiemChuyenCan(),
                studentmark.getDiemGiuaKy(),
                studentmark.getDiemThi(),
                studentmark.getDiemTongKet(),
                studentmark.getXepLoai(),
                studentmark.getMaMonHoc()});

        }

    }

    /*studentmarkk.getId(), studentmarkk.getName(), studentmarkk.getTenmon(),
                 studentmarkk.getDiem15(),
                 studentmarkk.getDiem45(), studentmarkk.getDiemthi(),studentmarkk.getDiemtongket(),studentmarkk.getXeploai(), studentmarkk.getMamh()*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tensv = new javax.swing.JTextField();
        idsv = new javax.swing.JTextField();
        mamh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        trolai = new javax.swing.JButton();
        j = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        diem15 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        diem45 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        diemthi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        diemtongket = new javax.swing.JTextField();
        btntinhdiemtongket = new javax.swing.JButton();
        xeploai = new javax.swing.JTextField();
        lammoi = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        studenttablemark = new javax.swing.JTable();
        combomon = new javax.swing.JComboBox<>();
        btnclear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnx = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ten Sinh Vien");

        jLabel2.setText("ID Sinh Vien");

        jLabel3.setText("Ten Mon Hoc");

        mamh.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        mamh.setEnabled(false);

        jLabel4.setText("Ma Mon Hoc");

        jLabel5.setText("Tim Kiem");

        btnsearch.setText("Tim Kiem");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        sua.setText("Edit");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        trolai.setText("Back");

        j.setText("Xep Loai");

        jLabel8.setText("Diem Thanh Phan");

        jLabel9.setText("Diem Giua Ky");

        jLabel10.setText("Diem Thi");

        diemthi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                diemthiKeyReleased(evt);
            }
        });

        jLabel11.setText("Diem Tong Ket");

        btntinhdiemtongket.setText("Tinh Diem Tong Ket");
        btntinhdiemtongket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntinhdiemtongketActionPerformed(evt);
            }
        });

        lammoi.setText("Refresh");
        lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lammoiActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        studenttablemark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        studenttablemark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studenttablemarkMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(studenttablemark);

        combomon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toan Cao Cap", "Toan Cao Cap 2", "Mac Lenin", "Lap Trinh Can Ban", "Lap Trinh Java", "Anh Van" }));
        combomon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combomonItemStateChanged(evt);
            }
        });
        combomon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomonActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("QUAN LY DIEM SINH VIEN");

        btnx.setText("X");
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idsv)
                    .addComponent(tensv)
                    .addComponent(btnsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(combomon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mamh, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(diem15, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(diemtongket, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diemthi)
                                    .addComponent(diem45))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(152, 152, 152)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(trolai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(sua, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(156, 156, 156))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnx)
                                        .addContainerGap())))
                            .addComponent(xeploai, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(963, 963, 963)
                        .addComponent(btntinhdiemtongket))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tensv)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(diem45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(diemthi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(diem15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnx)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert)
                            .addComponent(sua)
                            .addComponent(lammoi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete)
                            .addComponent(trolai)
                            .addComponent(btnclear))
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(combomon))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(diemtongket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mamh)))
                            .addComponent(xeploai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btntinhdiemtongket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        /* int row = studenttablemark.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(MarkManagerStudentFrame.this, "Vui Long Chon Hoc Sinh", "Loi", JOptionPane.ERROR_MESSAGE);

        } else {

            int id = Integer.valueOf(String.valueOf(studenttablemark.getValueAt(row, 0)));
            new EditStudentMarkFrame(id).setVisible(true);
            this.dispose();
            

        }*/

        update();

    }//GEN-LAST:event_suaActionPerformed

    public void SelectedRow() {

        int row = studenttablemark.getSelectedRow();
        idsv.setText(studenttablemark.getValueAt(row, 0).toString());
        tensv.setText(studenttablemark.getValueAt(row, 1).toString());
        combomon.setSelectedItem(studenttablemark.getValueAt(row, 2).toString());
        diem15.setText(studenttablemark.getValueAt(row, 3).toString());
        diem45.setText(studenttablemark.getValueAt(row, 4).toString());
        diemthi.setText(studenttablemark.getValueAt(row, 5).toString());

        diemtongket.setText(studenttablemark.getValueAt(row, 6).toString());
        xeploai.setText(studenttablemark.getValueAt(row, 7).toString());
        mamh.setText(studenttablemark.getValueAt(row, 8).toString());

    }

    public void update() {

        studentMark.setId(String.valueOf(idsv.getText()));
        studentMark.setName(tensv.getText());
        studentMark.setTenMonHoc(String.valueOf(combomon.getSelectedItem()));
        studentMark.setDiemChuyenCan(diem15.getText());
        studentMark.setDiemGiuaKy(diem45.getText());
        studentMark.setDiemThi(diemthi.getText());
        studentMark.setDiemTongKet(diemtongket.getText());
        studentMark.setXepLoai(xeploai.getText());
        studentMark.setMaMonHoc(mamh.getText());

        studentMarkController.updateStudentMark(studentMark);

        for (int i = 0; i <= studenttablemark.getRowCount(); i++) {
            if (studenttablemark.getValueAt(i, 0).equals(Integer.parseInt(idsv.getText()))) {
                studenttablemark.setValueAt(tensv.getText(), i, 1);
                break;
            }
        }
        JOptionPane.showMessageDialog(null, "Success");
    }

    public void calculatediem() {

        float diem15a = Float.parseFloat(this.diem15.getText());
        float diem45a = Float.parseFloat((this.diem45.getText()));
        float diemthi1 = Float.parseFloat(this.diemthi.getText());

        // Calculates total marks 
        double diemtongkett = ((0.2 * diem15a) + (0.2 * diem45a) + (0.6 * diemthi1));
        diemtongket.setText("" + diemtongkett);
        if (diemtongkett > 9) {
            xeploai.setText("Xuat Sac");
        } else if ((diemtongkett >= 8) && (diemtongkett <= 9)) {
            xeploai.setText("Gioi");
        } else if ((diemtongkett >= 7) && (diemtongkett < 8)) {
            xeploai.setText("Kha");
        } else if ((diemtongkett >= 6) && (diemtongkett <= 7)) {
            xeploai.setText("Trung Binh");
        } else if ((diemtongkett >= 5) && (diemtongkett < 6)) {
            xeploai.setText("Yeu");
        } else if ((diemtongkett < 5)) {
            xeploai.setText("Kem, Khong Dat");
        }

    }

    public void setmamonhoc() {
        Object mon = combomon.getSelectedItem();

        /*combomon.addItem("Toan Cao Cap");
       combomon.addItem("Toan Cao Cap 2");
       combomon.addItem("Mac Lenin");
       combomon.addItem("Cong Nghe Thong Tin");
       combomon.addItem("Lap Trinh Java");
       combomon.addItem("Anh Van");*/
        if ("Toan Cao Cap".equals(mon)) {
            mamh.setText("111");
        } else if ("Toan Cao Cap 2".equals(mon)) {
            mamh.setText("112");
        } else if ("Mac Lenin".equals(mon)) {
            mamh.setText("113");
        } else if ("Lap Trinh Can Ban".equals(mon)) {
            mamh.setText("114");
        } else if ("Lap Trinh Java".equals(mon)) {
            mamh.setText("115");
        } else if ("Anh Van".equals(mon)) {
            mamh.setText("116");
        }

    }

    public void comboMon() {

        studentMark.setTenMonHoc(combomon.getSelectedItem().toString());

    }


    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:

        new FindStudentMarkFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsearchActionPerformed


    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:

        studentMark.setId(idsv.getText());
        studentMark.setName(tensv.getText());
        studentMark.setTenMonHoc(combomon.getSelectedItem().toString());
        //studentmark.setTenmon(tenmh.getText());
        studentMark.setDiemChuyenCan(diem15.getText());
        studentMark.setDiemGiuaKy(diem45.getText());
        studentMark.setDiemThi(diemthi.getText());
        studentMark.setDiemTongKet(diemtongket.getText());
        studentMark.setXepLoai(xeploai.getText());
        studentMark.setMaMonHoc(mamh.getText());
        studentMarkController.addStudentMark(studentMark);
        defaultTableModel.addRow(studentMark.toObjects());
        JOptionPane.showMessageDialog(null, "Success");


    }//GEN-LAST:event_insertActionPerformed

    private void lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lammoiActionPerformed
        // TODO add your handling code here:
        //Coi lai phan refresh
        defaultTableModel.setRowCount(0);
        setdata(studentMarkController.getAllMark());
    }//GEN-LAST:event_lammoiActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:

        int row = studenttablemark.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(MarkManagerStudentFrame.this, "Vui Long Chon Sinh Vien", "Loi", JOptionPane.ERROR_MESSAGE);

        } else {

            int confirm = JOptionPane.showConfirmDialog(MarkManagerStudentFrame.this, "Ban Chac Chan Muon Xoa?");

            if (confirm == JOptionPane.YES_OPTION) {
                int id = Integer.valueOf(String.valueOf(studenttablemark.getValueAt(row, 0)));
                studentMarkController.deleteStudentMark(id);
                defaultTableModel.setRowCount(0);
                setdata(studentMarkController.getAllMark());
                JOptionPane.showMessageDialog(null, "Success");
            }

        }


    }//GEN-LAST:event_btndeleteActionPerformed

    private void studenttablemarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studenttablemarkMouseClicked
        // TODO add your handling code here:
        SelectedRow();

    }//GEN-LAST:event_studenttablemarkMouseClicked

    private void combomonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_combomonActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:

        idsv.setText(null);
        tensv.setText(null);
        diem15.setText(null);
        diem45.setText(null);
        diemthi.setText(null);
        diemtongket.setText(null);
        xeploai.setText(null);
        mamh.setText(null);
        JOptionPane.showMessageDialog(null, "Success");
    }//GEN-LAST:event_btnclearActionPerformed

    private void combomonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combomonItemStateChanged
        // TODO add your handling code here:
        setmamonhoc();

    }//GEN-LAST:event_combomonItemStateChanged

    private void btntinhdiemtongketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntinhdiemtongketActionPerformed
        // TODO add your handling code here:
        new TinhDiemTongKetFrame().setVisible(true);

    }//GEN-LAST:event_btntinhdiemtongketActionPerformed

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnxActionPerformed


    private void diemthiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diemthiKeyReleased
        // TODO add your handling code here:
        calculatediem();
    }//GEN-LAST:event_diemthiKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarkManagerStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarkManagerStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarkManagerStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarkManagerStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarkManagerStudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btntinhdiemtongket;
    private javax.swing.JButton btnx;
    private javax.swing.JComboBox<String> combomon;
    private javax.swing.JTextField diem15;
    private javax.swing.JTextField diem45;
    private javax.swing.JTextField diemthi;
    private javax.swing.JTextField diemtongket;
    private javax.swing.JTextField idsv;
    private javax.swing.JButton insert;
    private javax.swing.JLabel j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lammoi;
    private javax.swing.JTextField mamh;
    private javax.swing.JTable studenttablemark;
    private javax.swing.JButton sua;
    public javax.swing.JTextField tensv;
    private javax.swing.JButton trolai;
    private javax.swing.JTextField xeploai;
    // End of variables declaration//GEN-END:variables
}
